If you want to help me financially, you can send cryptocurrency to my wallets:
btc: 1E6G9K89Lk86NPaRe2tjvWDgVuSM4YhPgu .
xmr: 438fr2CeS65SQvUGdSKr1uC1vTcW4PbCQ38hHGqFBSUkfvSw2pzWDuk2j9JG9QybcwMrG6xzj98w3BQkCkCZAz37GsLxXfF .
By this action, you will provoke to develop a new version for CR: MP 0.3.7. [i]I am now in a difficult financial situation, so[/i] I will be glad of any help
