If you want to help me financially, you can send cryptocurrency to my wallets:
Bitcoin: 1E6G9K89Lk86NPaRe2tjvWDgVuSM4YhPgu
Monero : 438fr2CeS65SQvUGdSKr1uC1vTcW4PbCQ38hHGqFBSUkfvSw2pzWDuk2j9JG9QybcwMrG6xzj98w3BQkCkCZAz37GsLxXfF
By this action, you will provoke to develop a new version for CR: MP 0.3.7. 
I am now in a difficult financial situation, so I will be glad of any help.
if at least $ 200 is collected, I promise to update the trainer.  in which I will fix all the bugs of the current version.  I also adapt it for updated anti-cheats.  In general, there will be a working version of the trainer
